from collections import Counter
import statistics
from tenx.engine import _run_decision_core
from empirical.backbone import run_empirical_reference
SEEDS=[3,9,15,25,33,45,57]
def run_campaign():
    runs=[_run_decision_core(s) for s in SEEDS]; names=[r['decision']['design']['name'] for r in runs]; modal,n=Counter(names).most_common(1)[0]; margins=[r['decision']['reliability_lcb']-.95 for r in runs]; costs=[r['decision']['cost'] for r in runs]; errs=[statistics.mean(r['model_validation']['range_accel_cost']) for r in runs]; emp=run_empirical_reference(); premium=float(emp.get('domain_diagnostics',{}).get('metrics',{}).get('robustness_premium_vs_cheapest_usd',0)); minmargin=min(margins)
    state='ARCHITECTURE_RELEASE_REVIEW' if minmargin>=0 and n/len(runs)>=.7 else 'HOLD_FOR_VERIFICATION'
    return {'campaign':'Architecture Verification Campaign','campaign_identity':'reliability margin + surrogate verification frontier','scenario_count':len(runs),'scenario_seeds':SEEDS,'state':state,'selected_architecture':modal,'selection_share':round(n/len(runs),4),'reliability_margin':round(minmargin,6),'mean_reliability_margin':round(statistics.mean(margins),6),'mean_surrogate_nrmse':round(statistics.mean(errs),5),'mean_selected_cost':round(statistics.mean(costs),2),'modeled_robustness_premium_vs_cheapest':premium,'scenario_matrix':[{'seed':s,'architecture':r['decision']['design']['name'],'reliability_lcb':r['decision']['reliability_lcb'],'reliability_margin':round(margins[i],6),'cost':r['decision']['cost'],'mean_nrmse':round(errs[i],5)} for i,(s,r) in enumerate(zip(SEEDS,runs))],'ai_synthesis':{'why':f'{modal} selected in {n}/{len(runs)} verification campaigns; worst reliability margin={minmargin:.4f}.','challenge':'Nominal KPI/cost advantage is insufficient if finite-sample confidence or surrogate validity is weak.','recommended_operator_action':'Advance the confidence-certified architecture to exact physics/thermal/Pareto verification.','abstention_conditions':['negative reliability margin','high surrogate disagreement','design outside training envelope','unclosed hard requirement']},'action_queue':['review requirement margin matrix','inspect surrogate error/disagreement','run exact physics/thermal verification','review robustness premium','approve or HOLD architecture'],'human_authority':'VEHICLE_ARCHITECTURE_REVIEW','autonomous_execution':False,'empirical_provenance':{'mode':emp.get('data_mode'),'promotion':emp.get('empirical_promotion')}}
